package org.springframework.samples.petclinic.entryPointsForAssertions;

import org.springframework.samples.petclinic.autoGeneratedAssertions.AuthoritiesAssert;


import org.springframework.samples.petclinic.autoGeneratedAssertions.BDCarreraAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.BaseEntityAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.CategoryAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.FormRellenarBDAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.GranPremioAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.LeagueAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.LineupAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.LineupTestsAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.MessageAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.NamedEntityAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.OfferAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.PersonAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.PilotAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.RecordAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.RecordCircuitoAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.RecordMejorVueltaAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.RecordPoleAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.RecordVueltaRapidaAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.RecruitAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.ResultAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.StatusAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.TablaConsultasAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.TeamAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.TeamModelTestAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.TransactionAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.UserAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.UserRevEntityAssert;
import org.springframework.samples.petclinic.autoGeneratedAssertions.UserRevisionListenerAssert;
import org.springframework.samples.petclinic.model.Authorities;
import org.springframework.samples.petclinic.model.BDCarrera;
import org.springframework.samples.petclinic.model.BaseEntity;
import org.springframework.samples.petclinic.model.Category;
import org.springframework.samples.petclinic.model.FormRellenarBD;
import org.springframework.samples.petclinic.model.GranPremio;
import org.springframework.samples.petclinic.model.League;
import org.springframework.samples.petclinic.model.Lineup;
import org.springframework.samples.petclinic.model.LineupTests;
import org.springframework.samples.petclinic.model.Message;
import org.springframework.samples.petclinic.model.NamedEntity;
import org.springframework.samples.petclinic.model.Offer;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.samples.petclinic.model.Pilot;
import org.springframework.samples.petclinic.model.Record;
import org.springframework.samples.petclinic.model.RecordCircuito;
import org.springframework.samples.petclinic.model.RecordMejorVuelta;
import org.springframework.samples.petclinic.model.RecordPole;
import org.springframework.samples.petclinic.model.RecordVueltaRapida;
import org.springframework.samples.petclinic.model.Recruit;
import org.springframework.samples.petclinic.model.Result;
import org.springframework.samples.petclinic.model.Status;
import org.springframework.samples.petclinic.model.TablaConsultas;
import org.springframework.samples.petclinic.model.Team;
import org.springframework.samples.petclinic.model.TeamModelTest;
import org.springframework.samples.petclinic.model.Transaction;
import org.springframework.samples.petclinic.model.User;
import org.springframework.samples.petclinic.model.audit.UserRevEntity;
import org.springframework.samples.petclinic.model.audit.UserRevisionListener;

/**
 * Entry point for assertions of different data types. Each method in this class is a static factory for the
 * type-specific assertion objects.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class Assertions {

  /**
   * Creates a new instance of <code>{@link AuthoritiesAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static AuthoritiesAssert assertThat(Authorities actual) {
    return new AuthoritiesAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link BDCarreraAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static BDCarreraAssert assertThat(BDCarrera actual) {
    return new BDCarreraAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link BaseEntityAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static BaseEntityAssert assertThat(BaseEntity actual) {
    return new BaseEntityAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link CategoryAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static CategoryAssert assertThat(Category actual) {
    return new CategoryAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link FormRellenarBDAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static FormRellenarBDAssert assertThat(FormRellenarBD actual) {
    return new FormRellenarBDAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link GranPremioAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static GranPremioAssert assertThat(GranPremio actual) {
    return new GranPremioAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link LeagueAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static LeagueAssert assertThat(League actual) {
    return new LeagueAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link LineupAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static LineupAssert assertThat(Lineup actual) {
    return new LineupAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link LineupTestsAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static LineupTestsAssert assertThat(LineupTests actual) {
    return new LineupTestsAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link MessageAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static MessageAssert assertThat(Message actual) {
    return new MessageAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link NamedEntityAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static NamedEntityAssert assertThat(NamedEntity actual) {
    return new NamedEntityAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link OfferAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static OfferAssert assertThat(Offer actual) {
    return new OfferAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link PersonAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static PersonAssert assertThat(Person actual) {
    return new PersonAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link PilotAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static PilotAssert assertThat(Pilot actual) {
    return new PilotAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RecordAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordAssert assertThat(Record actual) {
    return new RecordAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RecordCircuitoAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordCircuitoAssert assertThat(RecordCircuito actual) {
    return new RecordCircuitoAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RecordMejorVueltaAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordMejorVueltaAssert assertThat(RecordMejorVuelta actual) {
    return new RecordMejorVueltaAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RecordPoleAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordPoleAssert assertThat(RecordPole actual) {
    return new RecordPoleAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RecordVueltaRapidaAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordVueltaRapidaAssert assertThat(RecordVueltaRapida actual) {
    return new RecordVueltaRapidaAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RecruitAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecruitAssert assertThat(Recruit actual) {
    return new RecruitAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link ResultAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static ResultAssert assertThat(Result actual) {
    return new ResultAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link StatusAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static StatusAssert assertThat(Status actual) {
    return new StatusAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link TablaConsultasAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static TablaConsultasAssert assertThat(TablaConsultas actual) {
    return new TablaConsultasAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link TeamAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static TeamAssert assertThat(Team actual) {
    return new TeamAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link TeamModelTestAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static TeamModelTestAssert assertThat(TeamModelTest actual) {
    return new TeamModelTestAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link TransactionAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static TransactionAssert assertThat(Transaction actual) {
    return new TransactionAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link TransactionTypeAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */


  /**
   * Creates a new instance of <code>{@link UserAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static UserAssert assertThat(User actual) {
    return new UserAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link UserRevEntityAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static UserRevEntityAssert assertThat(UserRevEntity actual) {
    return new UserRevEntityAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link UserRevisionListenerAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static UserRevisionListenerAssert assertThat(UserRevisionListener actual) {
    return new UserRevisionListenerAssert(actual);
  }

  /**
   * Creates a new <code>{@link Assertions}</code>.
   */
  protected Assertions() {
    // empty
  }
}
