package org.springframework.samples.petclinic.entryPointsForAssertions;

import org.springframework.samples.petclinic.autoGeneratedAssertions.*;
import org.springframework.samples.petclinic.model.audit.*;
import org.springframework.samples.petclinic.model.*;

/**
 * Entry point for assertions of different data types. Each method in this class is a static factory for the
 * type-specific assertion objects.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class Assertions {

  /**
   * Creates a new instance of <code>{@link AuthoritiesAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static AuthoritiesAssert assertThat(Authorities actual) {
    return new AuthoritiesAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link BDCarreraAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static BDCarreraAssert assertThat(BDCarrera actual) {
    return new BDCarreraAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link BaseEntityAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static BaseEntityAssert assertThat(BaseEntity actual) {
    return new BaseEntityAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link CategoryAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static CategoryAssert assertThat(Category actual) {
    return new CategoryAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link FormRellenarBDAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static FormRellenarBDAssert assertThat(FormRellenarBD actual) {
    return new FormRellenarBDAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link GranPremioAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static GranPremioAssert assertThat(GranPremio actual) {
    return new GranPremioAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link LeagueAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static LeagueAssert assertThat(League actual) {
    return new LeagueAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link LineupAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static LineupAssert assertThat(Lineup actual) {
    return new LineupAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link LineupTestsAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static LineupTestsAssert assertThat(LineupTests actual) {
    return new LineupTestsAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link MessageAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static MessageAssert assertThat(Message actual) {
    return new MessageAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link NamedEntityAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static NamedEntityAssert assertThat(NamedEntity actual) {
    return new NamedEntityAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link OfferAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static OfferAssert assertThat(Offer actual) {
    return new OfferAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link PersonAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static PersonAssert assertThat(Person actual) {
    return new PersonAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link PilotAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static PilotAssert assertThat(Pilot actual) {
    return new PilotAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RecordAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordAssert assertThat(Record actual) {
    return new RecordAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RecordCircuitoAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordCircuitoAssert assertThat(RecordCircuito actual) {
    return new RecordCircuitoAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RecordMejorVueltaAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordMejorVueltaAssert assertThat(RecordMejorVuelta actual) {
    return new RecordMejorVueltaAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RecordPoleAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordPoleAssert assertThat(RecordPole actual) {
    return new RecordPoleAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RecordVueltaRapidaAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordVueltaRapidaAssert assertThat(RecordVueltaRapida actual) {
    return new RecordVueltaRapidaAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RecruitAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecruitAssert assertThat(Recruit actual) {
    return new RecruitAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link ResultAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static ResultAssert assertThat(Result actual) {
    return new ResultAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link RolAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static RolAssert assertThat(Rol actual) {
    return new RolAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link StatusAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static StatusAssert assertThat(Status actual) {
    return new StatusAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link TablaConsultasAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static TablaConsultasAssert assertThat(TablaConsultas actual) {
    return new TablaConsultasAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link TeamAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static TeamAssert assertThat(Team actual) {
    return new TeamAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link TeamModelTestAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static TeamModelTestAssert assertThat(TeamModelTest actual) {
    return new TeamModelTestAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link TeamValidatorTestsAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static TeamValidatorTestsAssert assertThat(TeamValidatorTests actual) {
    return new TeamValidatorTestsAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link TransactionAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static TransactionAssert assertThat(Transaction actual) {
    return new TransactionAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link TransactionTypeAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static TransactionTypeAssert assertThat(TransactionType actual) {
    return new TransactionTypeAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link UserAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static UserAssert assertThat(User actual) {
    return new UserAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link UserRevEntityAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static UserRevEntityAssert assertThat(UserRevEntity actual) {
    return new UserRevEntityAssert(actual);
  }

  /**
   * Creates a new instance of <code>{@link UserRevisionListenerAssert}</code>.
   *
   * @param actual the actual value.
   * @return the created assertion object.
   */
  @org.assertj.core.util.CheckReturnValue
  public static UserRevisionListenerAssert assertThat(UserRevisionListener actual) {
    return new UserRevisionListenerAssert(actual);
  }

  /**
   * Creates a new <code>{@link Assertions}</code>.
   */
  protected Assertions() {
    // empty
  }
}
