dist: trusty
language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "gii-is-dp1"
    token:
      secure: "hX7xv/26a+mc86RYmW/9N1cTQgExe5KFgkH6sZkVV7ZRiWPIAb+HTMRsiqeaKCAqSDBquEE9/gFzxq80tqbjKlhRQRIEpPyDifc4wuFG+iGpA/MztZz6dInyiq5y8LRHlPsBbAq233PqtoDcVxk9agfAuygYcUquTb9XCVLcEtdBWsSBxAyX3KIcWyujjYR4su1vpYfL+tetY1X85DhNoDMZNvR56cg4+umdGYakp0CiLfqXElOjJEB7UxXAkami9itU7I4hk8iwfV/IYzE1+BqDw/OdO1BgBBx0YDr8kBN0EtyhFI4rBgbK10ZlC+l6hHYCIM0pgXFtncFPnEvv1dyqS/6Oc9NKRqg2azTFJBBZ47Mvq7Xrbot/fHubOr07YLqD13xOTFQ8ZH1pzk3C21yEi4O8o9ui6QOYjrHZ7B3QkV/8sp79alA60c5ZbP2CWQHB1gA8wKWbEXq66L7CIyoUsZR8JBgJRyj5v1+haGk2WuJcWYPHibSdNOlsy61y9hUr27F1oYh4MQobnZ6q/MgpNiURVd4pAPP3ml+zSpOdb8fCTnudCS8k9tw135A0N7fMuTl78jhE2ntJdtSMDRDBV3sgZ3EHMkbxR5cWhYeb1K+KlQkLtQ0SbleuOE4IG3bBVReNaWdyJU3oPbzFBwFggwjKuFoOaVyFRHGt55s="
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'
script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gii-is-DP1_dp1-2020-g2-05
  - mvn test -Dspring-boot.run.profiles=mysql-travis
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
