dist: trusty
language: java
jdk: oraclejdk11

services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'

addons:
  sonarcloud:
    organization: "gii-is-dp1"
    token:
      secure: "PXbyFlcQxQay98P9+QpXa5xcKQO0PlIlqjcj2lDZMd/qLVlzb3NfB7R1dtRRznyyL/njhfq4Ueq8zt/mGBcLWsXd96RcOGoObF18tFs0GtSDSyRmIdlMk+g57vYFPqSo5mRaSqaXxm6TMm+OZmFm7MVGoPZg+9wI4ZehY9XjCSB22kwj2qvzJkTq/kYipYw3NbRlFY7+Y+EIX+3e/vz3+BeGIAJgNB4EyLJf63m55N3/K/CuEfgvMEcAHdQ3CdsIheX0Vuf4jRvyXi0dUOIWv0QONLe0pxz3onCnipzV81MTb6PhmRjwI43mmjpogsRti9fQScb+ZlDwW8pj4/m9OK+zyj+U0eliFPXJAeX+EzbgiJgKVlLfW5jcJ9pAV1hxee/4xSYw8CofIY1zNpb1zRrcJ2Y0C5JT9xpPxwOp2/Ltf7yDIR04jRRCY48ofeQaV46UCC1djKsskzw0EZzcRDoQljITHXzk/gaFU5qkl2TCZtZJtCXse4FyFcwH+zJiF/HQB2gL8tAiJcSLhgah7+dI0L+d+avoBgjanHzl58X5/cvr4CEYxqpcQFsRSqKhK3tPx4zRa3S6k9MigWevCxfDzCBhw98Pll0X3JRQ/LI5BqCtCNrVJe5f9TLSllB9uhs2Q2UQ7wfFE0u3Ki0fnTWfpvJx9vKLAopjncqleQc="

script:
  - mvn test -Dspring-boot.run.profiles=mysql-travis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gii-is-DP1_dp1-2020-g2-05
