package org.springframework.samples.petclinic.autoGeneratedAssertions;

import org.assertj.core.api.AbstractObjectAssert;
import org.springframework.samples.petclinic.model.TeamValidatorTests;

/**
 * Abstract base class for {@link TeamValidatorTests} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractTeamValidatorTestsAssert<S extends AbstractTeamValidatorTestsAssert<S, A>, A extends TeamValidatorTests> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractTeamValidatorTestsAssert}</code> to make assertions on actual TeamValidatorTests.
   * @param actual the TeamValidatorTests we want to make assertions on.
   */
  protected AbstractTeamValidatorTestsAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
