package org.springframework.samples.petclinic.autoGeneratedAssertions;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;
import org.springframework.samples.petclinic.model.audit.UserRevEntity;

/**
 * Abstract base class for {@link UserRevEntity} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractUserRevEntityAssert<S extends AbstractUserRevEntityAssert<S, A>, A extends UserRevEntity> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractUserRevEntityAssert}</code> to make assertions on actual UserRevEntity.
   * @param actual the UserRevEntity we want to make assertions on.
   */
  protected AbstractUserRevEntityAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual UserRevEntity's username is equal to the given one.
   * @param username the given username to compare the actual UserRevEntity's username to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserRevEntity's username is not equal to the given one.
   */
  public S hasUsername(String username) {
    // check that actual UserRevEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting username of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualUsername = actual.getUsername();
    if (!Objects.areEqual(actualUsername, username)) {
      failWithMessage(assertjErrorMessage, actual, username, actualUsername);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
