package org.springframework.samples.petclinic.autoGeneratedAssertions;

import org.assertj.core.api.AbstractObjectAssert;
import org.springframework.samples.petclinic.model.LineupTests;

/**
 * Abstract base class for {@link LineupTests} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractLineupTestsAssert<S extends AbstractLineupTestsAssert<S, A>, A extends LineupTests> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractLineupTestsAssert}</code> to make assertions on actual LineupTests.
   * @param actual the LineupTests we want to make assertions on.
   */
  protected AbstractLineupTestsAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
