package org.springframework.samples.petclinic.autoGeneratedAssertions;

import org.assertj.core.api.AbstractObjectAssert;
import org.springframework.samples.petclinic.model.audit.UserRevisionListener;

/**
 * Abstract base class for {@link UserRevisionListener} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractUserRevisionListenerAssert<S extends AbstractUserRevisionListenerAssert<S, A>, A extends UserRevisionListener> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractUserRevisionListenerAssert}</code> to make assertions on actual UserRevisionListener.
   * @param actual the UserRevisionListener we want to make assertions on.
   */
  protected AbstractUserRevisionListenerAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
