package org.springframework.samples.petclinic.autoGeneratedAssertions;

import org.assertj.core.api.AbstractComparableAssert;
import org.springframework.samples.petclinic.model.TransactionType;

/**
 * Abstract base class for {@link TransactionType} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractTransactionTypeAssert<S extends AbstractTransactionTypeAssert<S, A>, A extends TransactionType> extends AbstractComparableAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractTransactionTypeAssert}</code> to make assertions on actual TransactionType.
   * @param actual the TransactionType we want to make assertions on.
   */
  protected AbstractTransactionTypeAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
