package org.springframework.samples.petclinic.autoGeneratedAssertions;

import org.assertj.core.api.AbstractComparableAssert;
import org.springframework.samples.petclinic.model.Rol;

/**
 * Abstract base class for {@link Rol} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractRolAssert<S extends AbstractRolAssert<S, A>, A extends Rol> extends AbstractComparableAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractRolAssert}</code> to make assertions on actual Rol.
   * @param actual the Rol we want to make assertions on.
   */
  protected AbstractRolAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
