package org.springframework.samples.petclinic.autoGeneratedAssertions;

import org.springframework.samples.petclinic.model.Rol;

/**
 * {@link Rol} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractRolAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class RolAssert extends AbstractRolAssert<RolAssert, Rol> {

  /**
   * Creates a new <code>{@link RolAssert}</code> to make assertions on actual Rol.
   * @param actual the Rol we want to make assertions on.
   */
  public RolAssert(Rol actual) {
    super(actual, RolAssert.class);
  }

  /**
   * An entry point for RolAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myRol)</code> and get specific assertion with code completion.
   * @param actual the Rol we want to make assertions on.
   * @return a new <code>{@link RolAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static RolAssert assertThat(Rol actual) {
    return new RolAssert(actual);
  }
}
