package org.springframework.samples.petclinic.autoGeneratedAssertions;

import org.springframework.samples.petclinic.model.TeamValidatorTests;

/**
 * {@link TeamValidatorTests} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTeamValidatorTestsAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class TeamValidatorTestsAssert extends AbstractTeamValidatorTestsAssert<TeamValidatorTestsAssert, TeamValidatorTests> {

  /**
   * Creates a new <code>{@link TeamValidatorTestsAssert}</code> to make assertions on actual TeamValidatorTests.
   * @param actual the TeamValidatorTests we want to make assertions on.
   */
  public TeamValidatorTestsAssert(TeamValidatorTests actual) {
    super(actual, TeamValidatorTestsAssert.class);
  }

  /**
   * An entry point for TeamValidatorTestsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTeamValidatorTests)</code> and get specific assertion with code completion.
   * @param actual the TeamValidatorTests we want to make assertions on.
   * @return a new <code>{@link TeamValidatorTestsAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static TeamValidatorTestsAssert assertThat(TeamValidatorTests actual) {
    return new TeamValidatorTestsAssert(actual);
  }
}
