package org.springframework.samples.petclinic.autoGeneratedAssertions;

import org.springframework.samples.petclinic.model.TeamModelTest;

/**
 * {@link TeamModelTest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTeamModelTestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class TeamModelTestAssert extends AbstractTeamModelTestAssert<TeamModelTestAssert, TeamModelTest> {

  /**
   * Creates a new <code>{@link TeamModelTestAssert}</code> to make assertions on actual TeamModelTest.
   * @param actual the TeamModelTest we want to make assertions on.
   */
  public TeamModelTestAssert(TeamModelTest actual) {
    super(actual, TeamModelTestAssert.class);
  }

  /**
   * An entry point for TeamModelTestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTeamModelTest)</code> and get specific assertion with code completion.
   * @param actual the TeamModelTest we want to make assertions on.
   * @return a new <code>{@link TeamModelTestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static TeamModelTestAssert assertThat(TeamModelTest actual) {
    return new TeamModelTestAssert(actual);
  }
}
