package org.springframework.samples.petclinic.customAssertions;

import org.assertj.core.api.AbstractComparableAssert;
import org.springframework.samples.petclinic.model.Status;

/**
 * Abstract base class for {@link Status} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractStatusAssert<S extends AbstractStatusAssert<S, A>, A extends Status> extends AbstractComparableAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractStatusAssert}</code> to make assertions on actual Status.
   * @param actual the Status we want to make assertions on.
   */
  protected AbstractStatusAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
