package org.springframework.samples.petclinic.customAssertions;

import org.assertj.core.util.Objects;
import org.springframework.samples.petclinic.model.AbstractBaseEntityAssert;
import org.springframework.samples.petclinic.model.NamedEntity;

/**
 * Abstract base class for {@link NamedEntity} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractNamedEntityAssert<S extends AbstractNamedEntityAssert<S, A>, A extends NamedEntity> extends AbstractBaseEntityAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractNamedEntityAssert}</code> to make assertions on actual NamedEntity.
   * @param actual the NamedEntity we want to make assertions on.
   */
  protected AbstractNamedEntityAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual NamedEntity's name is equal to the given one.
   * @param name the given name to compare the actual NamedEntity's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual NamedEntity's name is not equal to the given one.
   */
  public S hasName(String name) {
    // check that actual NamedEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
