package org.springframework.samples.petclinic.customAssertions;

import org.springframework.samples.petclinic.model.Record;

/**
 * {@link Record} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractRecordAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class RecordAssert extends AbstractRecordAssert<RecordAssert, Record> {

  /**
   * Creates a new <code>{@link RecordAssert}</code> to make assertions on actual Record.
   * @param actual the Record we want to make assertions on.
   */
  public RecordAssert(Record actual) {
    super(actual, RecordAssert.class);
  }

  /**
   * An entry point for RecordAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myRecord)</code> and get specific assertion with code completion.
   * @param actual the Record we want to make assertions on.
   * @return a new <code>{@link RecordAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordAssert assertThat(Record actual) {
    return new RecordAssert(actual);
  }
}
