package org.springframework.samples.petclinic.customAssertions;

import org.springframework.samples.petclinic.model.Recruit;

/**
 * {@link Recruit} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractRecruitAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class RecruitAssert extends AbstractRecruitAssert<RecruitAssert, Recruit> {

  /**
   * Creates a new <code>{@link RecruitAssert}</code> to make assertions on actual Recruit.
   * @param actual the Recruit we want to make assertions on.
   */
  public RecruitAssert(Recruit actual) {
    super(actual, RecruitAssert.class);
  }

  /**
   * An entry point for RecruitAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myRecruit)</code> and get specific assertion with code completion.
   * @param actual the Recruit we want to make assertions on.
   * @return a new <code>{@link RecruitAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecruitAssert assertThat(Recruit actual) {
    return new RecruitAssert(actual);
  }
}
