package org.springframework.samples.petclinic.customAssertions;

import org.springframework.samples.petclinic.model.Result;

/**
 * {@link Result} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractResultAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ResultAssert extends AbstractResultAssert<ResultAssert, Result> {

  /**
   * Creates a new <code>{@link ResultAssert}</code> to make assertions on actual Result.
   * @param actual the Result we want to make assertions on.
   */
  public ResultAssert(Result actual) {
    super(actual, ResultAssert.class);
  }

  /**
   * An entry point for ResultAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myResult)</code> and get specific assertion with code completion.
   * @param actual the Result we want to make assertions on.
   * @return a new <code>{@link ResultAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ResultAssert assertThat(Result actual) {
    return new ResultAssert(actual);
  }
}
