package org.springframework.samples.petclinic.customAssertions;

import org.springframework.samples.petclinic.model.Status;

/**
 * {@link Status} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractStatusAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class StatusAssert extends AbstractStatusAssert<StatusAssert, Status> {

  /**
   * Creates a new <code>{@link StatusAssert}</code> to make assertions on actual Status.
   * @param actual the Status we want to make assertions on.
   */
  public StatusAssert(Status actual) {
    super(actual, StatusAssert.class);
  }

  /**
   * An entry point for StatusAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myStatus)</code> and get specific assertion with code completion.
   * @param actual the Status we want to make assertions on.
   * @return a new <code>{@link StatusAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static StatusAssert assertThat(Status actual) {
    return new StatusAssert(actual);
  }
}
