package org.springframework.samples.petclinic.customAssertions;

import org.springframework.samples.petclinic.model.TransactionType;

/**
 * {@link TransactionType} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTransactionTypeAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class TransactionTypeAssert extends AbstractTransactionTypeAssert<TransactionTypeAssert, TransactionType> {

  /**
   * Creates a new <code>{@link TransactionTypeAssert}</code> to make assertions on actual TransactionType.
   * @param actual the TransactionType we want to make assertions on.
   */
  public TransactionTypeAssert(TransactionType actual) {
    super(actual, TransactionTypeAssert.class);
  }

  /**
   * An entry point for TransactionTypeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTransactionType)</code> and get specific assertion with code completion.
   * @param actual the TransactionType we want to make assertions on.
   * @return a new <code>{@link TransactionTypeAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static TransactionTypeAssert assertThat(TransactionType actual) {
    return new TransactionTypeAssert(actual);
  }
}
