package org.springframework.samples.petclinic.customAssertions;

import org.springframework.samples.petclinic.model.Transaction;

/**
 * {@link Transaction} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTransactionAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class TransactionAssert extends AbstractTransactionAssert<TransactionAssert, Transaction> {

  /**
   * Creates a new <code>{@link TransactionAssert}</code> to make assertions on actual Transaction.
   * @param actual the Transaction we want to make assertions on.
   */
  public TransactionAssert(Transaction actual) {
    super(actual, TransactionAssert.class);
  }

  /**
   * An entry point for TransactionAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTransaction)</code> and get specific assertion with code completion.
   * @param actual the Transaction we want to make assertions on.
   * @return a new <code>{@link TransactionAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static TransactionAssert assertThat(Transaction actual) {
    return new TransactionAssert(actual);
  }
}
