package org.springframework.samples.petclinic.customAssertions;

import org.springframework.samples.petclinic.model.audit.UserRevisionListener;

/**
 * {@link UserRevisionListener} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractUserRevisionListenerAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class UserRevisionListenerAssert extends AbstractUserRevisionListenerAssert<UserRevisionListenerAssert, UserRevisionListener> {

  /**
   * Creates a new <code>{@link UserRevisionListenerAssert}</code> to make assertions on actual UserRevisionListener.
   * @param actual the UserRevisionListener we want to make assertions on.
   */
  public UserRevisionListenerAssert(UserRevisionListener actual) {
    super(actual, UserRevisionListenerAssert.class);
  }

  /**
   * An entry point for UserRevisionListenerAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myUserRevisionListener)</code> and get specific assertion with code completion.
   * @param actual the UserRevisionListener we want to make assertions on.
   * @return a new <code>{@link UserRevisionListenerAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static UserRevisionListenerAssert assertThat(UserRevisionListener actual) {
    return new UserRevisionListenerAssert(actual);
  }
}
