package org.springframework.samples.dreamgp.autoGeneratedAssertions;

import org.assertj.core.api.AbstractObjectAssert;
import org.springframework.samples.dreamgp.model.TeamModelTest;

/**
 * Abstract base class for {@link TeamModelTest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractTeamModelTestAssert<S extends AbstractTeamModelTestAssert<S, A>, A extends TeamModelTest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractTeamModelTestAssert}</code> to make assertions on actual TeamModelTest.
   * @param actual the TeamModelTest we want to make assertions on.
   */
  protected AbstractTeamModelTestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
