package org.springframework.samples.dreamgp.autoGeneratedAssertions;

import org.assertj.core.api.AbstractComparableAssert;
import org.springframework.samples.dreamgp.model.Category;

/**
 * Abstract base class for {@link Category} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractCategoryAssert<S extends AbstractCategoryAssert<S, A>, A extends Category> extends AbstractComparableAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractCategoryAssert}</code> to make assertions on actual Category.
   * @param actual the Category we want to make assertions on.
   */
  protected AbstractCategoryAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
