package org.springframework.samples.dreamgp.autoGeneratedAssertions;

import org.springframework.samples.dreamgp.model.Authorities;

/**
 * {@link Authorities} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractAuthoritiesAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class AuthoritiesAssert extends AbstractAuthoritiesAssert<AuthoritiesAssert, Authorities> {

  /**
   * Creates a new <code>{@link AuthoritiesAssert}</code> to make assertions on actual Authorities.
   * @param actual the Authorities we want to make assertions on.
   */
  public AuthoritiesAssert(Authorities actual) {
    super(actual, AuthoritiesAssert.class);
  }

  /**
   * An entry point for AuthoritiesAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myAuthorities)</code> and get specific assertion with code completion.
   * @param actual the Authorities we want to make assertions on.
   * @return a new <code>{@link AuthoritiesAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static AuthoritiesAssert assertThat(Authorities actual) {
    return new AuthoritiesAssert(actual);
  }
}
