package org.springframework.samples.dreamgp.autoGeneratedAssertions;

import org.springframework.samples.dreamgp.model.BDCarrera;

/**
 * {@link BDCarrera} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractBDCarreraAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class BDCarreraAssert extends AbstractBDCarreraAssert<BDCarreraAssert, BDCarrera> {

  /**
   * Creates a new <code>{@link BDCarreraAssert}</code> to make assertions on actual BDCarrera.
   * @param actual the BDCarrera we want to make assertions on.
   */
  public BDCarreraAssert(BDCarrera actual) {
    super(actual, BDCarreraAssert.class);
  }

  /**
   * An entry point for BDCarreraAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myBDCarrera)</code> and get specific assertion with code completion.
   * @param actual the BDCarrera we want to make assertions on.
   * @return a new <code>{@link BDCarreraAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static BDCarreraAssert assertThat(BDCarrera actual) {
    return new BDCarreraAssert(actual);
  }
}
