package org.springframework.samples.dreamgp.autoGeneratedAssertions;

import org.springframework.samples.dreamgp.model.LineupTests;

/**
 * {@link LineupTests} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractLineupTestsAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class LineupTestsAssert extends AbstractLineupTestsAssert<LineupTestsAssert, LineupTests> {

  /**
   * Creates a new <code>{@link LineupTestsAssert}</code> to make assertions on actual LineupTests.
   * @param actual the LineupTests we want to make assertions on.
   */
  public LineupTestsAssert(LineupTests actual) {
    super(actual, LineupTestsAssert.class);
  }

  /**
   * An entry point for LineupTestsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myLineupTests)</code> and get specific assertion with code completion.
   * @param actual the LineupTests we want to make assertions on.
   * @return a new <code>{@link LineupTestsAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static LineupTestsAssert assertThat(LineupTests actual) {
    return new LineupTestsAssert(actual);
  }
}
