package org.springframework.samples.dreamgp.autoGeneratedAssertions;

import org.springframework.samples.dreamgp.model.RecordVueltaRapida;

/**
 * {@link RecordVueltaRapida} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractRecordVueltaRapidaAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class RecordVueltaRapidaAssert extends AbstractRecordVueltaRapidaAssert<RecordVueltaRapidaAssert, RecordVueltaRapida> {

  /**
   * Creates a new <code>{@link RecordVueltaRapidaAssert}</code> to make assertions on actual RecordVueltaRapida.
   * @param actual the RecordVueltaRapida we want to make assertions on.
   */
  public RecordVueltaRapidaAssert(RecordVueltaRapida actual) {
    super(actual, RecordVueltaRapidaAssert.class);
  }

  /**
   * An entry point for RecordVueltaRapidaAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myRecordVueltaRapida)</code> and get specific assertion with code completion.
   * @param actual the RecordVueltaRapida we want to make assertions on.
   * @return a new <code>{@link RecordVueltaRapidaAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordVueltaRapidaAssert assertThat(RecordVueltaRapida actual) {
    return new RecordVueltaRapidaAssert(actual);
  }
}
