package org.springframework.samples.dreamgp.autoGeneratedAssertions;

import org.springframework.samples.dreamgp.model.RecordMejorVuelta;

/**
 * {@link RecordMejorVuelta} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractRecordMejorVueltaAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class RecordMejorVueltaAssert extends AbstractRecordMejorVueltaAssert<RecordMejorVueltaAssert, RecordMejorVuelta> {

  /**
   * Creates a new <code>{@link RecordMejorVueltaAssert}</code> to make assertions on actual RecordMejorVuelta.
   * @param actual the RecordMejorVuelta we want to make assertions on.
   */
  public RecordMejorVueltaAssert(RecordMejorVuelta actual) {
    super(actual, RecordMejorVueltaAssert.class);
  }

  /**
   * An entry point for RecordMejorVueltaAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myRecordMejorVuelta)</code> and get specific assertion with code completion.
   * @param actual the RecordMejorVuelta we want to make assertions on.
   * @return a new <code>{@link RecordMejorVueltaAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static RecordMejorVueltaAssert assertThat(RecordMejorVuelta actual) {
    return new RecordMejorVueltaAssert(actual);
  }
}
